name: Comparar tokens

on: push

jobs:
    comparar-tokens:
        runs-on: self-hosted
        steps:
            - name: Comparar tokens
              env:
                DEV_TOKEN: ${{secrets.DEV_TOKEN}}
              run: |
                if [ "$DEV_TOKEN" = "$LOCAL_DEV_TOKEN" ]; then
                    echo "los tokens coinciden"
                else
                    echo "los tokens NO coinciden"
                    exit 1
                fi
